name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install g++
      run: sudo apt-get install -y g++
    
    - name: Compile
      run: g++ -o P1 P1.cpp
    
    - name: Run
      run: ./P1
